export const qk = {
  courses: ['courses'] as const,
  categories: ['categories'] as const,
  courseLanguages: ['courseLanguages'] as const,
  course: (slug: string) => ['course', slug] as const,
  courseById: (id: string) => ['courseById', id] as const,
  enrollments: ['enrollments'] as const,
  myOrders: ['me', 'orders'] as const,
  adminStats: ['admin', 'stats'] as const,
  publishedTest: (courseId: string) => ['publishedTest', courseId] as const,
  adminCourses: ['admin', 'courses'] as const,
  adminMedia: ['admin', 'media'] as const,
  adminTests: ['admin', 'tests'] as const,
  adminAnnouncements: ['admin', 'announcements'] as const,
  adminOrders: ['admin', 'orders'] as const,
  adminDirectory: ['admin', 'directory'] as const,
  purchases: ['purchases'] as const,
  progress: (courseId: string) => ['progress', courseId] as const,
  certificates: ['certificates'] as const,
}
