export type CourseSlideType = 'image' | 'pdf' | 'video' | 'pptx' | 'ppt'

export type CourseSlide = {
  id: string
  type: CourseSlideType
  url: string
  title?: string
  /** Internal slide count for a single .pptx deck. */
  deckSlideCount?: number
  /**
   * Server-side rendered PNG image URLs for each page/slide in this deck or PDF.
   * Generated by LibreOffice at upload time and stored here so the frontend can
   * display slides as plain images instead of running pptx-preview in the browser.
   */
  renderedSlideUrls?: string[]
}
