export type CourseSlideType = 'image' | 'pdf' | 'video' | 'pptx' | 'ppt'

export type CourseSlideRenderStatus = 'pending' | 'ready' | 'failed'

/** Never persist 'generating' — a crash mid-call must leave this as 'pending' (retryable
 *  by the reconciliation sweep), not stuck in a state nothing will ever revisit. */
export type NarrationStatus = 'pending' | 'ready' | 'failed'

export type SlideNarrationLang = {
  text?: string
  audioUrl?: string
  /** Seconds of the generated clip. Feeds LearnerUnit.minDwellSec so "Next" can't
   *  unlock before the narration for this page has finished playing. */
  durationSec?: number
  status: NarrationStatus
  error?: string
  updatedAt?: string
}

export type SlidePageNarration = {
  /** True when the page is a divider/title-only page — narration is just the spoken title. */
  titleOnly?: boolean
  /** The renderedSlideUrls[i] (or image slide's own url) this entry was generated from.
   *  A mismatch against the current source means the page was re-rendered/replaced and
   *  this entry is stale — regenerate instead of trusting index position alone. */
  sourceUrl: string
  /** Keyed by language code (matches frontend i18n supportedLngs, e.g. 'en' | 'es'). */
  lang: Record<string, SlideNarrationLang>
}

export type CourseSlide = {
  id: string
  type: CourseSlideType
  url: string
  title?: string
  /** Original upload filename for admin playlist UI. */
  fileName?: string
  /** Internal slide count for a single .pptx deck. */
  deckSlideCount?: number
  /** PDF page count (set after server render). */
  pdfPageCount?: number
  /** Video length in seconds (from client probe or server). */
  durationSec?: number
  /** PDF render pipeline status. */
  renderStatus?: CourseSlideRenderStatus
  /**
   * Server-side rendered PNG image URLs for each page/slide in this deck or PDF.
   * Generated by LibreOffice at upload time and stored here so the frontend can
   * display slides as plain images instead of running pptx-preview in the browser.
   */
  renderedSlideUrls?: string[]
  /** Video-only: replaces the given PDF page in the learner view. */
  pageReplace?: {
    pdfSlideId: string
    pageNumber: number
    mode?: 'replace' | 'after'
  }
  /**
   * AI-generated caption + narration per rendered page, index-aligned to
   * renderedSlideUrls (pdf/pptx), or a single entry describing `url` itself
   * (plain `image` slides). Never set for `video` slides.
   */
  narration?: SlidePageNarration[]
}
