export type CourseSlideType = 'image' | 'pdf' | 'video' | 'pptx' | 'ppt'

export type CourseSlideRenderStatus = 'pending' | 'ready' | 'failed'

export type CourseSlide = {
  id: string
  type: CourseSlideType
  url: string
  title?: string
  /** Original upload filename for admin playlist UI. */
  fileName?: string
  /** Internal slide count for a single .pptx deck. */
  deckSlideCount?: number
  /** PDF page count (set after server render). */
  pdfPageCount?: number
  /** Video length in seconds (from client probe or server). */
  durationSec?: number
  /** PDF render pipeline status. */
  renderStatus?: CourseSlideRenderStatus
  /**
   * Server-side rendered PNG image URLs for each page/slide in this deck or PDF.
   * Generated by LibreOffice at upload time and stored here so the frontend can
   * display slides as plain images instead of running pptx-preview in the browser.
   */
  renderedSlideUrls?: string[]
  /** Video-only: replaces the given PDF page in the learner view. */
  pageReplace?: {
    pdfSlideId: string
    pageNumber: number
  }
}
