export type CourseLanguage = {
  id: string
  code: string
  name: string
}

export const DEFAULT_COURSE_LANGUAGE_ID = 'lang-en'

export type Category = {
  id: string
  name: string
  slug: string
  parentId: string | null
  /** Shown on completion certificates for courses in this category. */
  certificationText: string
}

export type CourseSlideType = 'image' | 'pdf' | 'video' | 'pptx' | 'ppt'

export type CourseSlideRenderStatus = 'pending' | 'ready' | 'failed'

export type CourseSlide = {
  id: string
  type: CourseSlideType
  url: string
  title?: string
  fileName?: string
  /** Number of slides inside a .pptx deck. */
  deckSlideCount?: number
  pdfPageCount?: number
  durationSec?: number
  renderStatus?: CourseSlideRenderStatus
  /**
   * Server-side rendered PNG image URLs (one per page/slide), generated by
   * LibreOffice at upload time. When present, the viewer shows these images
   * directly instead of running pptx-preview in the browser — instant display,
   * no parsing wait, and accurate rendering for all PPTX/PDF content.
   */
  renderedSlideUrls?: string[]
  /** Admin-only client preview (stripped before save). */
  previewDataUrl?: string
}

export type Course = {
  id: string
  slug: string
  title: string
  summary: string
  description: string
  categoryId: string
  /** Instruction language (course_languages.id). */
  languageId: string
  priceCents: number
  /** Admin sale discount 0–100; reflected on catalog and checkout. */
  discountPercent?: number
  /** List price after course discount (from API). */
  salePriceCents?: number
  durationMinutes: number
  slideCount: number
  /** Days until certificate expires after issue; null/undefined = no expiry. */
  certificateValidityDays?: number | null
  /** @deprecated Legacy image-only slides; use `slides`. */
  slideImageUrls?: string[]
  /** Ordered learner content: images, PDFs, PowerPoint (.pptx), or videos. */
  slides?: CourseSlide[]
  imageUrl: string
  published: boolean
  /** Homepage "Popular online courses" section. */
  popular: boolean
}

export type UserRole = 'learner' | 'admin'

export type UserSession = {
  email: string
  name: string
  role: UserRole
}

export type Purchase = {
  courseId: string
  purchasedAt: string
  orderId: string
}

export type Progress = {
  courseId: string
  slideIndex: number
  maxSlideIndex?: number
  audioTimeSec: number
  updatedAt: string
  completedSlides: boolean
  testPassed?: boolean
}

export type AppNotification = {
  id: string
  title: string
  body: string
  type: string
  read: boolean
  createdAt: string
}

export type Certificate = {
  id: string
  /** Public numeric ID; shown as #100001. */
  certificateNumber?: number
  courseId?: string | null
  courseName: string
  source?: 'platform' | 'manual'
  notes?: string | null
  userName: string
  issuedAt: string
  /** Snapshot of category certification line at issue time. */
  certificationText?: string
  categoryId?: string
  /** ISO date when the credential expires, if configured on the course. */
  expiresAt?: string | null
  userId?: string
}

export type MediaAsset = {
  id: string
  label: string
  url: string
  kind: 'image' | 'audio' | 'document' | 'other'
  createdAt: string
  /** Set when file was chosen from disk upload. */
  source?: 'url' | 'upload'
  fileName?: string | null
}

/** One selectable choice on a knowledge-check question. */
export type TestAnswerOption = {
  id: string
  label: string
  /** Classic single-answer MCQ: exactly one option per question should be true. */
  isCorrect: boolean
}

/** A single question with its own multi-choice answers. */
export type TestQuestion = {
  id: string
  prompt: string
  options: TestAnswerOption[]
}

/** Assessment attached to one course; pass = enough questions answered correctly vs `passPercent`. */
export type AdminTest = {
  id: string
  courseId: string
  title: string
  /** Minimum % of questions that must be correct (e.g. 80 = 8/10). */
  passPercent: number
  /** 0 = no limit; otherwise learners have this many minutes to finish. */
  timeLimitMinutes: number
  published: boolean
  updatedAt: string
  questions: TestQuestion[]
}

export type Announcement = {
  id: string
  title: string
  body: string
  createdAt: string
  status: 'draft' | 'sent'
  sentAt: string | null
}

export type AdminDirectoryUser = {
  id?: string
  email: string
  name: string
  role: 'learner' | 'admin'
  testFailCount?: number
  certificateCount?: number
  /** Server-managed admin; not editable in admin UI. */
  protected?: boolean
}

export type AdminUserDetail = {
  user: { id: string; email: string; name: string; role: string }
  enrollments: {
    id: string
    courseId: string
    courseTitle: string
    orderId: string
    purchasedAt: string
    refunded: boolean
    testAttemptsRemaining: number
    attemptsExhausted: boolean
  }[]
  orders: {
    orderId: string
    purchasedAt: string
    courseId: string
    courseTitle: string
    amountCents: number
    refunded: boolean
  }[]
  testAttempts: {
    id: string
    courseId: string
    courseTitle: string
    attemptNumber: number
    scorePercent: number
    passPercent: number
    passed: boolean
    timedOut: boolean
    submittedAt: string
  }[]
  testFailCount: number
  certificates: {
    id: string
    certificateNumber: number
    courseName: string
    source: string
    issuedAt: string
    expiresAt: string | null
  }[]
}
